<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-windows</TargetFrameworks>
		<Nullable>enable</Nullable>
		<IsAotCompatible>true</IsAotCompatible>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<PublishAot>true</PublishAot>
		<Platforms>AnyCPU</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.DisableRuntimeMarshallingAttribute"></AssemblyAttribute>
	</ItemGroup>

	<ItemGroup>
		<Reference Include="DirectN">
			<HintPath>External\DirectN.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<Using Include="DirectN" />
		<Using Include="WindowsTaskScheduler" />
		<Using Include="System" />
		<Using Include="System.Collections.Concurrent" />
		<Using Include="System.Collections.Generic" />
		<Using Include="System.ComponentModel" />
		<Using Include="System.Diagnostics.CodeAnalysis" />
		<Using Include="System.Globalization" />
		<Using Include="System.IO" />
		<Using Include="System.Linq" />
		<Using Include="System.Numerics" />
		<Using Include="System.Reflection" />
		<Using Include="System.Runtime.Versioning" />
		<Using Include="System.Runtime.CompilerServices" />
		<Using Include="System.Runtime.InteropServices" />
		<Using Include="System.Runtime.InteropServices.Marshalling" />
		<Using Include="System.Text.Json" />
		<Using Include="System.Text.Json.Serialization.Metadata" />
		<Using Include="System.Threading" />
		<Using Include="System.Threading.Tasks" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="External\" />
	</ItemGroup>

</Project>
